version: 0.0
os: linux
files:
  - source: .
    destination: /usr/share/applications/exp
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /usr/share/applications/exp
    pattern: '**'
    except: [logs/*]
    owner: ec2-user
    group: ec2-user
    mode: 644
    type:
      - file
      - directory
permissions:
  - object: /usr/share/applications/exp
    pattern: 'logs'
    owner: www
    group: www
    mode: 744
    type:
      - file
      - directory
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: www
